### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by marklove5102** [NMTuan/ezBookmarks2#1]
node14  18 20都是同一个错误 低于14 yarn都会直接下载依赖报错不能低于14
````
root@f05b90cf96f3:/# git co https://github.com/NMTuan/ezBookmarks2
Cloning into 'ezBookmarks2'...
remote: Enumerating objects: 1143, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1143 (delta 0), reused 1 (delta 0), pack-reused 1142
Receiving objects: 100% (1143/1143), 339.84 KiB | 443.00 KiB/s, done.
Resolving deltas: 100% (697/697), done.
root@f05b90cf96f3:/# cd ezBookmarks2
root@f05b90cf96f3:/ezBookmarks2# yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > simplebar-vue@1.8.0-alpha.0" has incorrect peer dependency "vue@^2.5.17".
[4/4] Building fresh packages...
Done in 43.24s.
root@f05b90cf96f3:/ezBookmarks2# yarn run 
yarn run v1.22.19
info Commands available from binary scripts: esbuild, jiti, jsesc, nanoid, node-which, parser, resolve, rollup, sass, unocss, uuid, vite, vue-demi-fix, vue-demi-switch
info Project commands
   - build
      vite build
   - dev
      vite
   - preview
      vite preview
question Which command would you like to run?: build
$ vite build
vite v3.2.5 building for production...
✓ 52 modules transformed.
Could not resolve './commonDialog.vue' from options/components/BaseIndexSearchEngine.vue
error during build:
Error: Could not resolve './commonDialog.vue' from options/components/BaseIndexSearchEngine.vue
    at error (file:///ezBookmarks2/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.handleResolveId (file:///ezBookmarks2/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22156:24)
    at file:///ezBookmarks2/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22119:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@f05b90cf96f3:/ezBookmarks2# node -v
v14.21.3
````

**Comment by NMTuan** [comment]
![image](https://github.com/NMTuan/ezBookmarks2/assets/2149763/f87ba58f-5aba-4b7b-82db-f69415dccd67)

![image](https://github.com/NMTuan/ezBookmarks2/assets/2149763/04ffe423-d603-47bb-9762-0a1ef0c259f6)

我这里能过呢？

ps. 这项目有些久了，虽然我一直在用，但没有什么更新，所以可能没什么时间支持。

市场上直接安装即可，源码主要用来学习，打包过不过问题不大：）

https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E5%8D%95%E4%B9%A6%E7%AD%BE2/kkbcimhjbielpnbdikekamomnfafepbh?hl=zh-CN

https://chromewebstore.google.com/detail/%E7%AE%80%E5%8D%95%E4%B9%A6%E7%AD%BE2/hgiffeojndgjffiedjacogcecppkaikn?hl=zh-CN

**Comment by marklove5102** [comment]
可能要在win下才能编译吧！
我用了一个全新的18 docker 也是同样的问题。
我只是在搜集代码 然后改成我要的。学习下
![image](https://github.com/NMTuan/ezBookmarks2/assets/12666917/054a5e70-d366-4669-9542-a275420b302a)
